### ISSUE TITLE
Question: How to @group_by multiple columns?

### ISSUE THREAD

**Issue by metanoid** [davidanthoff/Queryverse.jl#5]
In the Introduction to Queryverse notebook [here](https://www.juliabox.com/notebook/notebooks/tutorials/intro-to-the-queryverse/AnthoffQueryverseJune2018.ipynb) the @group_by macro seems to work as follows:

* The first argument is the grouping column or function
* The second argument is optional, but can be used to specify a column or function to pass into the grouping as data?  It's not clear to me

My question is this:  What is the correct way to group by multiple columns, rather than just 1?  For example, in the notebook above, we have:
`cars |> @groupby(_.Origin, _.Acceleration) |> @map({Origin=_.key, MeanAcceleration=mean(_)})`
So we are grouping by Origin and passing in Acceleration as the data in each group.
What if I wanted to group by both Origin and number of cylinders?
Is there a best practice way to do that?

**Comment by davidanthoff** [comment]
``cars |> @groupby({_.origin, _.Cylinders}, _.Acceleration)`` should do the trick. The first argument to ``@groupby`` can by any julia expression, so here we are returning a named tuple, and then things get grouped by that named tuple.
